<template>
  <div v-if="comment" class="ml-4 mt-2 mb-4 border-l-2 border-bgSecondary-light dark:border-bgSecondary-dark">
    <div class="overflow-auto overflow-wrap break-words">
      <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
        <span v-if="comment.signer">
          <span v-if="showActionDetails">Author: </span>
          <ExtraBlockies :seed="comment.signer" :scale="2" class="inline-block mr-1" />
          <nuxt-link :to="`/authors/${comment.signer}`"
            class="text-colorPrimary-light dark:text-colorPrimary-dark hover:underline">

          <!-- client-only tags solve hydration mismatch warning -->
          <client-only>
            <span
              v-if="getMetadataByAddressNostr(comment.signer, 'username') && getMetadataByAddressNostr(comment.signer, 'username') !== 'none'"
              class="ml-1"
            >
              <span class="">
                {{ getMetadataByAddressNostr(comment.signer, 'username').slice(0,40) }}
              </span>
              <span class="text-sm">
                (Nostr)
              </span>
            </span>

            <span v-else class="ml-1" >
              <span v-if="enableAutoGeneratedNames">
                {{autoGeneratedName(comment.signer)}}
                ({{sliceAddress(comment.signer, 6)}})
              </span>
              <span v-else>
                {{sliceAddress(comment.signer, 6)}}
              </span>
            </span>
          </client-only>

          </nuxt-link>
          <ExtraAddressIcons
            v-if="comment.signer"
            :key="comment.signer"
            :value="comment.signer"
            :showCopyToClipboard="true"
            :showQrCode="true"
            :showExternalWebsite="true"
          />
        </span>
        <span v-if="showActionDetails">
          <span class="ml-1">
            <span class="signatureLabel">Signature: </span>
            <nuxt-link class="text-colorPrimary-light dark:text-colorPrimary-dark hover:underline"
              :to="`/news/${comment.signature}`">
            {{sliceAddress(comment.signature)}}
            </nuxt-link>
            <ExtraAddressIcons
              v-if="comment.signature"
              :key="comment.signature"
              :value="comment.signature"
              :showCopyToClipboard="true"
            />
          </span>
          <span v-if="comment.target">
            <span class="ml-1">Target: </span>
            <nuxt-link class="text-colorPrimary-light dark:text-colorPrimary-dark hover:underline"
              :to="`/news/?p=${comment.target}`">
              <span>
                {{sliceAddress(comment.target)}}
              </span>
            </nuxt-link>
            <ExtraAddressIcons
              v-if="comment.target"
              :key="comment.target"
              :value="comment.target"
              :showCopyToClipboard="true"
            />
          </span>
        </span>
        <!-- short URL -->
        <nuxt-link v-if="comment.signature && enableShortUrlsForWeb3Actions" :to="`/news/${comment.signature.slice(0,shortUrlsLengthOfWeb3Ids)}`" class="nuxt-link text-colorNotImportant-light dark:text-colorNotImportant-dark hover:text-colorPrimary-light dark:hover:text-colorPrimary-dark">
          <span v-if="comment.signed_time">
            ({{new Date(Date.parse(comment.signed_time)).toDateString()}})
          </span>
        </nuxt-link>
        <!-- full URL -->
        <nuxt-link v-if="comment.signature && !enableShortUrlsForWeb3Actions" :to="`/news/${comment.signature}`" class="nuxt-link text-colorNotImportant-light dark:text-colorNotImportant-dark hover:text-colorPrimary-light dark:hover:text-colorPrimary-dark">
          <span v-if="comment.signed_time">
            ({{new Date(Date.parse(comment.signed_time)).toDateString()}})
          </span>
        </nuxt-link>
      </div>

      <div>
        <h6 v-if="comment.title" class="font-bold">
          {{comment.title}}
        </h6>
      </div>

      <div v-if="comment.text" class="whitespace-pre-line my-1 pl-1">

        <!-- No iframe tags -->
        <div v-if="!isSignerAllowedIframe">
          <!-- Plain text -->
          <div v-if="!enableMarkdownInComments">
            {{comment.text}}
          </div>
          <!-- Markdown if enabled -->
          <div
            v-if="enableMarkdownInComments"
            v-dompurify-html="(marked(comment.text, {breaks:true}))"
          />
        </div>

        <!-- Iframe tags -->
        <div v-if="isSignerAllowedIframe">
          <div
            v-for="(textChunk, index) in arrayOfTextChunks"
            :key="randomNumber()"
          >
            <!-- Markdown if enabled -->
            <div
              v-if="enableMarkdownInComments && textChunk"
              v-dompurify-html="(marked(textChunk, {breaks:true}))"
            />
            <!-- Plain text if markdown is disabled -->
            <div v-if="!enableMarkdownInComments && textChunk">
              {{textChunk}}
            </div>
            <!-- HTML tags (e.g. iframe) -->
            <!--
              DOMPurify is not used so tags can be embedded.
              HTML tags in arrayOfHtmlTags are generated by the
              script and only for whitelisted users.
            -->
            <div
              v-if="arrayOfHtmlTags && arrayOfHtmlTags[index]"
              v-html="arrayOfHtmlTags[index]"
            />
          </div>
        </div>

      </div>

    </div>

    <div>
      <InfoPostCommentsCardReactionsBar :comment="comment" class="mr-1"/>

      <span v-if="showCommentsCount">
        <nuxt-link :to="`/news/?p=${comment.signature}`">
          <button v-if="comment.comments_count" class="inline-block mr-2 text-colorBlue-light dark:text-colorBlue-dark">
            <IconsComments class="w-4 inline-block "/>
            {{comment.comments_count}}
          </button>
        </nuxt-link>
      </span>

      <div v-if="enableNewWeb3ActionsAll && enableNewWeb3ActionsReply" class="inline-block">
        <div class="inline-block text-lg lg:text-base text-colorNotImportant-light dark:text-colorNotImportant-dark cursor-pointer hover:text-colorPrimary-light dark:hover:text-colorPrimary-dark" @click="toggleReplyForm">
          {{showReplyFormText}}
        </div>
      </div>

      <InfoPostCommentInputField v-if="showReplyForm" :target="comment.signature" @reply-submitted="replySubmitted" />
    </div>

    <!--
      Actions like replies and reactions can come from child
      comments, so we have to emit them up to InfoPostComments.
    -->
    <div v-if="comment.children" class="children">
      <InfoPostCommentsCard
        v-for="child in comment.children"
        :id="child.id"
        :key="child.id"
        :comment="child"
        :show-action-details="showActionDetails"
        @reply-submitted="replySubmitted"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import {marked} from 'marked'
import {Post, PostId} from '@/helpers/interfaces'

// Nostr usernames
import { storeToRefs } from 'pinia'
import {useProfilesStore} from '@/stores/useProfilesStore'
const profilesStore = useProfilesStore()
const { getMetadataByAddressNostr } = storeToRefs(profilesStore)

const {sliceAddress, randomNumber} = useUtils()
const {autoGeneratedName} = useUtils()
const env = useRuntimeConfig()?.public
const enableAutoGeneratedNames: boolean = env?.enableAutoGeneratedNames === 'false'? false : true
const enableMarkdownInComments = env?.enableMarkdownInComments === 'true'? true : false
const enableEmbedIframeTagsInComments = env?.enableEmbedIframeTagsInComments === 'true'? true : false
// New web3 actions are enabled by default if not disabled in .env
const enableNewWeb3ActionsAll: boolean = env?.enableNewWeb3ActionsAll === 'false'? false : true
const enableNewWeb3ActionsReply: boolean = env?.enableNewWeb3ActionsReply === 'false'? false : true
// Short URLs for web3 actions are enabled by default if not disabled in .env
const enableShortUrlsForWeb3Actions: boolean = env?.enableShortUrlsForWeb3Actions === 'false'? false : true
const shortUrlsLengthOfWeb3Ids: number = env?.shortUrlsLengthOfWeb3Ids ? Number(env?.shortUrlsLengthOfWeb3Ids) : 20
const {checkIfSignerAllowedIframe, getArrayOfArraysOfTextAndTags} = useHtmlTags()

const props = defineProps<{
  comment?: Post
  key?: PostId
  showActionDetails?: boolean
  showCommentsCount?: boolean
}>()

const emit = defineEmits<{
  (e: 'reply-submitted', target?: string | number | null): void
}>()

const replySubmitted = (target?: string | number | null) => {
  /* console.log('reply was submitted for target:', target) */
  showReplyForm.value = false
  showReplyFormText.value = 'reply'
  emit('reply-submitted', target)
}

const showReplyForm = ref(false)
const showReplyFormText = ref('reply')

const toggleReplyForm = () => {
      showReplyForm.value = !showReplyForm.value
      showReplyFormText.value = showReplyFormText.value === 'reply'
        ? 'hide'
        : 'reply'
    }

// Iframe tags
let isSignerAllowedIframe: boolean = false
let arrayOfTextChunks: string[] = ['']
let arrayOfHtmlTags: string[] = ['']

if (enableEmbedIframeTagsInComments) {
  // Check if a signer is allowed to embed iframe tags
  if (typeof(props?.comment?.signer) === 'string') {
    isSignerAllowedIframe = checkIfSignerAllowedIframe(props?.comment?.signer)
  }

  // Add iframe tags if text has any iframe URLs
  // WARNING: it's very important to check whether the
  // signer is allowed to add iframe tags because that's
  // a potential attack vector.
  if (typeof(props?.comment?.text) === 'string' && isSignerAllowedIframe) {
    const arrayOfArraysOfTextAndTags: string[][] = getArrayOfArraysOfTextAndTags(props?.comment)
    arrayOfTextChunks = arrayOfArraysOfTextAndTags[0]
    arrayOfHtmlTags = arrayOfArraysOfTextAndTags[1]
  }
}

// Add addresses to a list of addresses that should be checked
// for profile info (e.g. usernames) during an update function.
if (process.client) {
  if (
    props?.comment &&
    'signer' in props?.comment &&
    typeof(props?.comment.signer) === "string"
  ) {
    profilesStore.addAddress(props?.comment?.signer)
  }
}
</script>

<style scoped>

</style>
