<template>
  <div v-if="address && address.verified">
    <div v-if="address.value" class="text-base text-colorNotImportant-light dark:text-colorNotImportant-dark">
      <span>Author: </span>
      <ExtraBlockies
        :seed="address.value?.toString()"
        :scale="2"
        class="inline-block mr-1"
      />
      <nuxt-link :to="`/authors/${address.value?.toString()}`"
        class="text-colorPrimary-light dark:text-colorPrimary-dark hover:underline">

        <!-- client-only tags solve hydration mismatch warning -->
        <client-only>
            <span
              v-if="getMetadataByAddressNostr(address.value?.toString(), 'username') && getMetadataByAddressNostr(address.value?.toString(), 'username') !== 'none'"
              class="ml-1"
            >
              <span class="">
                {{ getMetadataByAddressNostr(address.value?.toString(), 'username').slice(0,40) }}
              </span>
              <span class="text-sm">
                (Nostr)
              </span>
            </span>

          <span v-else class="">
            <span v-if="enableAutoGeneratedNames">
              {{autoGeneratedName(address.value?.toString())}}
              ({{address.value?.toString().slice(0, 6)}}...{{address.value?.toString().slice(-4)}})
            </span>
            <span v-else>
              {{address.value?.toString().slice(0, 6)}}...{{address.value?.toString().slice(-4)}}
            </span>
          </span>
        </client-only>
      </nuxt-link>

      <ExtraAddressIcons
        v-if="address.value?.toString()"
        :key="address.value?.toString()"
        :value="address.value?.toString()"
        :showCopyToClipboard="true"
        :showQrCode="true"
        :showExternalWebsite="true"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import {SpasmEventAddressV2} from "@/helpers/interfaces"
import {storeToRefs} from 'pinia'
import {useProfilesStore} from '@/stores/useProfilesStore'
const profilesStore = useProfilesStore()
const {getMetadataByAddressNostr} = storeToRefs(profilesStore)
const env = useRuntimeConfig()?.public
const enableAutoGeneratedNames: boolean = env?.enableAutoGeneratedNames === 'false'? false : true
const {
  autoGeneratedName, 
} = useUtils()
const props = defineProps<{
  address?: SpasmEventAddressV2
  key?: string | number
}>()
</script>

<style scoped>
</style>
