<template>
  <div class="p-2">
    <client-only>
      <span id="top-anchor"></span>
      <div
        v-if="getMetadataByAddressNostr(author, 'picture') && getMetadataByAddressNostr(author, 'picture') !== 'none'"
        class="h-20 overflow-hidden"
      >
        <img
          :src="getMetadataByAddressNostr(author, 'picture') as string"
          alt="Nostr profile picture"
          class="h-20 object-cover"
        />
      </div>

      <div
        v-else
        class="h-20 overflow-hidden"
      >
        <ExtraBlockies v-if="author" :seed="author" :scale="10" />
      </div>
    </client-only>

    <div class="mt-2">
      <div v-if="enableAutoGeneratedNames">
        <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
          Auto-generated name:
        </div>
        <span class="overflow-auto overflow-wrap break-words">
          <span>{{autoGeneratedName(author)}}</span>
        </span>
      </div>
      <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
        <span v-if="npub">Address (hex):</span>
        <span v-else>Address:</span>
      </div>
      <span class="overflow-auto overflow-wrap break-words">
        {{ author }}
      </span>
      <ExtraAddressIcons
        v-if="author"
        :key="author"
        :value="author"
        :showCopyToClipboard="true"
        :showQrCode="true"
        :showExternalWebsite="true"
      />
    </div>

    <div v-if="npub">
      <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
        Address (npub):
      </div>
      <span class="overflow-auto overflow-wrap break-words">
        {{ npub }}
      </span>
      <ExtraAddressIcons
        v-if="npub"
        :key="npub"
        :value="npub"
        :showCopyToClipboard="true"
        :showQrCode="true"
        :showExternalWebsite="true"
      />
    </div>

    <!-- client-only tags solve hydration mismatch warning -->
    <client-only>
      <div v-if="getMetadataByAddressNostr(author, 'username') && getMetadataByAddressNostr(author, 'username') !== 'none'">
        <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
          Name:
        </div>
        <span class="text-xl font-bold">
          {{ getMetadataByAddressNostr(author, 'username') }}
        </span>
        <span class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
          (non-unique Nostr name)
        </span>
      </div>

      <div v-if="getMetadataByAddressNostr(author, 'about') && getMetadataByAddressNostr(author, 'about') !== 'none'">
        <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
          About:
        </div>
        <span class="">
          {{ getMetadataByAddressNostr(author, 'about') }}
        </span>
      </div>

      <div v-if="getMetadataByAddressNostr(author, 'website') && getMetadataByAddressNostr(author, 'website') !== 'none'">
        <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
          Website:
        </div>
        <span class="">
          {{ getMetadataByAddressNostr(author, 'website') }}
        </span>
      </div>
    </client-only>

    <!--
      client-only tags solve hydration mismatch warning,
      but rendering on the client side is bad for SEO,
      because author's posts are not rendered on the server
      side, so they are not being indexed by crawlers.
    -->
    <client-only>
      <div class="mt-4 mb-12">
        <div class="text-lg">
          Networks:
          <span
            class="cursor-pointer text-colorNotImportant-light dark:text-colorNotImportant-dark"
            :class="{ 'text-colorPrimary-light dark:text-colorPrimary-dark': selectedNetworkToDisplay === 'spasm' }"
            @click="selectNetworkToDisplay('spasm')"
          >
            Spasm
          </span>
          <span
            v-if="npub"
            class="cursor-pointer text-colorNotImportant-light dark:text-colorNotImportant-dark"
            :class="{ 'text-colorPrimary-light dark:text-colorPrimary-dark': selectedNetworkToDisplay === 'nostr' }"
            @click="selectNetworkToDisplay('nostr')"
          >
            Nostr
          </span>
        </div>
        <div class="cursor-pointer text-colorNotImportant-light dark:text-colorNotImportant-dark mb-4 hover:text-colorPrimary-light dark:hover:text-colorPrimary-dark"
          @click="toggleShowActionDetails()">
          {{showActionDetailsText}} details
        </div>

        <!-- Spasm network -->
        <div v-if="selectedNetworkToDisplay === 'spasm'">
          <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
            Spasm network:
          </div>
          <div v-if="areValidSpasmEventsV2(posts)">
            <InfoEventCommentsCard
              v-for="post in posts"
              :key="post.ids?.[0]?.value"
              :comment="post"
              :show-comments-count="false"
              :show-action-details="showActionDetails"
            />
          </div>
        </div>

        <!-- Nostr network -->
        <div v-if="selectedNetworkToDisplay === 'nostr'">
          <div v-if="getMessagesByAddressNostr(author) && hasValue(getMessagesByAddressNostr(author))">
            <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
              Nostr network:
            </div>
            <span class="">
              <!--
              {{ getMessagesByAddressNostr(author) }}
              -->
              <InfoEventCommentsCard
                v-for="event in spasm.convertManyToSpasm(getMessagesByAddressNostr(author))"
                :key="event?.ids?.[0]?.value || randomNumber()"
                :comment="event"
                :show-action-details="showActionDetails"
                :show-comments-count=false
              />
            </span>
          </div>
        </div>

      </div>
      <div class="w-32 mt-1 mb-16 cursor-pointer text-colorNotImportant-light dark:text-colorNotImportant-dark" @click="scrollToTop()">
        Scroll to top
      </div>
    </client-only>

  </div>
</template>

<script setup lang="ts">
import {SpasmEventV2} from '@/helpers/interfaces';
import { spasm } from 'spasm.js'

import { storeToRefs } from 'pinia'
import {useProfilesStore} from '@/stores/useProfilesStore'
const env = useRuntimeConfig()?.public
const enableAutoGeneratedNames: boolean = env?.enableAutoGeneratedNames === 'false'? false : true

const selectedNetworkToDisplay = ref("spasm")
const selectNetworkToDisplay = (
  newNetwork: string
): void => {
  if (!newNetwork) { return }
  selectedNetworkToDisplay.value = newNetwork
}

const { randomNumber } = useWeb3()

const {
  areValidSpasmEventsV2,
  autoGeneratedName,
  hasValue
} = useUtils()

const {
  toBeNpub
} = useNostr()

const profilesStore = useProfilesStore()
const {
  getMetadataByAddressNostr,
  getMessagesByAddressNostr
} = storeToRefs(profilesStore)

const { id } = useRoute().params

const scrollToTop = () => {
  const element = document.querySelector('#top-anchor');
  if (element) {
    element.scrollIntoView({ behavior: 'smooth', block: 'end' });
    /* element.scrollIntoView({ block: 'start' }); */
  }
}

if (process.client) {
  // Scroll to the top when author changes
  // Small delay to allow DOM to update
  setTimeout(scrollToTop, 300)
}

let author = ""
let npub: string | null = null

if (id) {
  if (typeof(id) === "string") {
    author = id.toLowerCase()
  } else if (typeof(id) === "number") {
    author = id.toString()
  }
}

if (
  author && typeof(author) === "string" && author.length === 64
) { npub = toBeNpub(author) }

const { getMockEventsByAddress} = useMocks()

const useMockedDataIfBackendIsDown = useRuntimeConfig()?.public
  ?.useMockedDataIfBackendIsDown === "true" ? true : false

const apiURL = useRuntimeConfig()?.public?.apiURL

const showActionDetails = ref(false)
const showActionDetailsText = ref('show')

let posts = reactive<SpasmEventV2[]>([])

let isError = ref<boolean>(false)

const path: string = `${apiURL}/api/authors/${author}`

const {data, error} = await useFetch(path)

if (error.value) {
  isError.value = true
  console.error(error.value)
}

if (data?.value) {
  const spasmEvents: SpasmEventV2[] | null =
    spasm.convertManyToSpasm(data.value)
  if (spasmEvents && areValidSpasmEventsV2(spasmEvents)) {
    posts = spasmEvents
  }
// Use mock posts for testing locally without backend
// if activated in the .env file.
} else if (
  useMockedDataIfBackendIsDown
) {
  posts = getMockEventsByAddress(author)
}

const toggleShowActionDetails = (): void => {
  showActionDetails.value = !showActionDetails.value
  showActionDetailsText.value = showActionDetailsText.value === 'show'
    ? 'hide'
    : 'show'
}

/**
  Nuxt.js uses server-side rendering (SSR) by default,
  so JavaScript code is initially run on the server,
  not in the browser. Since WebSockets are a browser API,
  they're not available on the server.
  To resolve this issue, the process.client property is used
  to conditionally run code only on the client:
*/

// Add a signer address to a list of addresses that should be
// updated once everything else is loaded.
// The update will fetch profiles associated with these addresses.
if (process.client) {
  if (
    author && 
    typeof(author) === "string"
  ) {
    profilesStore
      .addAddress(author, ["username", "relays", "messages"])
    profilesStore
      .updateAllProfiles(["username", "relays", "messages"])
  }
}

</script>

<style scoped>

</style>
